### ISSUE TITLE
Survey current state of lectures + code and see which require the most improvement

### ISSUE THREAD

**Issue by choldgraf** [neuro-data-science/neuro_data_science#8]

**Comment by choldgraf** [comment]
Just added a couple of stats lectures and reorganized the folders in the python section a bit. Perhaps we can have a brief meeting in the next weeks to discuss some other topics we could add. What do you think @JesseLivezey ?

**Comment by choldgraf** [comment]
@JesseLivezey can you upload the photo from our meeting here so that we can start building off of this? Then we can divide and conquer w/r/t to the material that's already there.

**Comment by JesseLivezey** [comment]
![img_20161205_131033](https://cloud.githubusercontent.com/assets/2081702/21112950/8bf00f4c-c05c-11e6-9864-088e5f22d08a.jpg)

**Comment by choldgraf** [comment]
Thanks! I'll formalize this into an issue and we can start iterating from there. Do you want to just divvy up the topics half/half? Do you want to take `basics` or `modeling`?

**Comment by JesseLivezey** [comment]
I can take ```modeling``` since I've done some work on it already. Half and
half sounds good.

**Comment by choldgraf** [comment]
sounds good - for now let's focus on the notebooks that are there and do numbers 2 and 3 (from the whiteboard) and then we can think about expanding topics later. I also met with Charles and I think he's gonna work to port Kendrick's lectures to python so maybe we can use those materials in the future

**Comment by choldgraf** [comment]
Going to keep track of this in #12 for the notebook standardizing and #13 for keeping track of the outline, and closing this issue
